# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11e10f13ee9d100e6284e5f06a1796fe637c6bd45bff910fb42b9e48a3d2fde0aa9381e4422994a32d42c2aac6ddc1b290fe52254f12e389ef4523f547c5cbcf

test:
  secret_key_base: 8ba5348068e5d4c0c6c6f1f447343134fcd15e7ae1677291c1be77f39da1f6568f3129b846bbc11966a45fbd5e0506f87b4af92d3031e511c1caed82bd678afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
